### ISSUE TITLE
Add workflow permissions for caolan/async

### ISSUE THREAD

**Issue by Devils-Knight** [Devils-Knight/Automate-PR#10]
```yml
fix-repo
name : caolan/async
```

**Comment by Devils-Knight** [comment]
Details of Secured workflow
```yml
    name: caolan
    repo: async
    path: .github/workflows/ci.yml
```

links:
repo: https://github.com/caolan/async
fork: https://github.com/Devils-Knight/async

> Secured Workflow
```yml
name: CI

on:
  push:
    branches-ignore:
      - "dependabot/**"
  pull_request:

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Checkout
        uses: actions/checkout@v2

      - name: ⎔ Setup node ${{ matrix.node }}
        uses: actions/setup-node@v2
        with:
          cache: npm

      - name: 📥 Download deps
        run: npm ci

      - name: 🧪 Run lint
        run: npm run lint

  build:
    permissions:
      actions: write  # for styfle/cancel-workflow-action to cancel/stop running workflows
      checks: write  # for coverallsapp/github-action to create new checks
      contents: read  # for actions/checkout to fetch code
    runs-on: ${{ matrix.os }}
    needs: lint
    strategy:
      fail-fast: false
      matrix:
        node:
          - 12
          - 14
          - 16
          - 17
        os: [ubuntu-latest]
        browser:
          - FirefoxHeadless
        include:
          - os: macos-latest
            node: 16
            browser: FirefoxHeadless
          - os: windows-latest
            node: 16
            browser: FirefoxHeadless

    steps:
      - name: 🛑 Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: ⬇️ Checkout
        uses: actions/checkout@v2

      - name: ⎔ Setup node ${{ matrix.node }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          cache: npm

      - name: 📥 Download deps
        run: npm ci

      - name: Run coverage
        run: npm test

      - name: Run browser tests
        if: matrix.node == 16
        run: npm run mocha-browser-test -- --browsers ${{ matrix.browser }}  --timeout 10000
        env:
          DISPLAY: :99.0

      - name: Coverage
        if: matrix.os == 'ubuntu-latest' && matrix.node == '16'
        run: npm run coverage && npx nyc report --reporter=lcov

      - name: Coveralls
        if: matrix.os == 'ubuntu-latest' && matrix.node == '16'
        uses: coverallsapp/github-action@1.1.3
        with:
            github-token: ${{ secrets.GITHUB_TOKEN }}

```
