### ISSUE TITLE
Automate PR

### ISSUE THREAD

**Issue by Devils-Knight** [Devils-Knight/Automate-PR#2]
```yml
topic : ci
min_star : 0
total_pr : 1
```

**Comment by Devils-Knight** [comment]
PR is added for ```yml
    name: jeremycook123
    repo: BitcoinConverterTDD
    path: .github/workflows/dotnet-core.yml
    ```

**Comment by Devils-Knight** [comment]
PR is added for
```yml
    name: jeremycook123
    repo: BitcoinConverterTDD
    path: .github/workflows/dotnet-core.yml
    fork: https://github.com/Devils-Knight/BitcoinConverterTDD
```

> Secured Workflow
```yml
name: bitcoinconverter.build

on: push

permissions:
  contents: read

jobs:
  build:

    permissions:
      checks: write  # for coverallsapp/github-action to create new checks
      contents: write  # for softprops/action-gh-release to create GitHub release
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.402
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal

    - name: Generate coverage report
      run: |
        ls -la
        mkdir -p BitcoinConverter.Tests/TestResults
        cd BitcoinConverter.Tests
        dotnet test /p:CollectCoverage=true /p:CoverletOutput=TestResults/ /p:CoverletOutputFormat=lcov

    - name: Publish coverage report to coveralls.io
      uses: coverallsapp/github-action@v1.1.2
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: BitcoinConverter.Tests/TestResults/coverage.info

    - name: Upload artifact - Windows
      uses: actions/upload-artifact@v1.0.0
      with:
        name: BitcoinConverter.Code.dll
        path: BitcoinConverter.Code/bin/Release/netcoreapp3.1/BitcoinConverter.Code.dll

    - name: Make Release
      uses: softprops/action-gh-release@v0.1.5
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files:
          BitcoinConverter.Code/bin/Release/netcoreapp3.1/BitcoinConverter.Code.dll
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

**Comment by Devils-Knight** [comment]
Details of Secured workflow
```yml
    name: aspacek
    repo: Letterboxd-user-film-compare
    path: .github/workflows/main.yml
```

links:
repo: https://github.com/aspacek/Letterboxd-user-film-compare
fork: https://github.com/Devils-Knight/Letterboxd-user-film-compare

> Secured Workflow
```yml
# This is a basic workflow to help you get started with Actions.

# Name: CI (Continuous Integration)
name: CI

# Controls when the action will run.
# This will run on 0th minute, 10th hour (UTC) = 4am MDT, every day of every month, Sun-Sat.
on:
  push:
  schedule:
    - cron: "0 10 * * 0-6"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
permissions:
  contents: read

jobs:

  # This workflow contains a job called "CIsetup"
  CIsetup:

    # The type of runner that the job will run on
    runs-on: macos-latest

    # Loop through all python 3.x versions:
    strategy:
      matrix:
        python-version: [3.5, 3.6, 3.7, 3.8, 3.9]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Checks-out the ability to run a python program here
    - uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}

    # Run the CI setup programs:
    - run: python CI/user_film_compare_CI_setup_user_user_1.py
    - run: python CI/user_film_compare_CI_setup_user_user_2.py
    - run: python CI/user_film_compare_CI_setup_user_user_3.py
    - run: python CI/user_film_compare_CI_setup_user_following_1.py
    - run: python CI/user_film_compare_CI_setup_user_following_2.py
    - run: python CI/user_film_compare_CI_setup_user_following_3.py
    - run: python CI/user_film_compare_CI_setup_user_followers_1.py
    - run: python CI/user_film_compare_CI_setup_user_followers_2.py
    - run: python CI/user_film_compare_CI_setup_user_followers_3.py

    # Save the output files:
    - uses: actions/upload-artifact@v1
      with:
        name: CI_test_user_user_1_${{ matrix.python-version }}
        path: CI/user_film_compare_CI_user_user_1.py
    - uses: actions/upload-artifact@v1
      with:
        name: CI_test_user_user_2_${{ matrix.python-version }}
        path: CI/user_film_compare_CI_user_user_2.py
    - uses: actions/upload-artifact@v1
      with:
        name: CI_test_user_user_3_${{ matrix.python-version }}
        path: CI/user_film_compare_CI_user_user_3.py
    - uses: actions/upload-artifact@v1
      with:
        name: CI_test_user_following_1_${{ matrix.python-version }}
        path: CI/user_film_compare_CI_user_following_1.py
    - uses: actions/upload-artifact@v1
      with:
        name: CI_test_user_following_2_${{ matrix.python-version }}
        path: CI/user_film_compare_CI_user_following_2.py
    - uses: actions/upload-artifact@v1
      with:
        name: CI_test_user_following_3_${{ matrix.python-version }}
        path: CI/user_film_compare_CI_user_following_3.py
    - uses: actions/upload-artifact@v1
      with:
        name: CI_test_user_followers_1_${{ matrix.python-version }}
        path: CI/user_film_compare_CI_user_followers_1.py
    - uses: actions/upload-artifact@v1
      with:
        name: CI_test_user_followers_2_${{ matrix.python-version }}
        path: CI/user_film_compare_CI_user_followers_2.py
    - uses: actions/upload-artifact@v1
      with:
        name: CI_test_user_followers_3_${{ matrix.python-version }}
        path: CI/user_film_compare_CI_user_followers_3.py

  # Another job called "CIrun"
  CIrun:

    # Needs output from earlier job:
    needs: CIsetup
    runs-on: macos-latest

    # Loop through all python 3.x versions:
    strategy:
      matrix:
        python-version: [3.6,3.7,3.8]

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Checks-out the ability to run a python program here
    - uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Grab the needed outputs:
    - uses: actions/download-artifact@v1
      with:
        name: CI_test_user_user_1_${{ matrix.python-version }}
    - uses: actions/download-artifact@v1
      with:
        name: CI_test_user_user_2_${{ matrix.python-version }}
    - uses: actions/download-artifact@v1
      with:
        name: CI_test_user_user_3_${{ matrix.python-version }}
    - uses: actions/download-artifact@v1
      with:
        name: CI_test_user_following_1_${{ matrix.python-version }}
    - uses: actions/download-artifact@v1
      with:
        name: CI_test_user_following_2_${{ matrix.python-version }}
    - uses: actions/download-artifact@v1
      with:
        name: CI_test_user_following_3_${{ matrix.python-version }}
    - uses: actions/download-artifact@v1
      with:
        name: CI_test_user_followers_1_${{ matrix.python-version }}
    - uses: actions/download-artifact@v1
      with:
        name: CI_test_user_followers_2_${{ matrix.python-version }}
    - uses: actions/download-artifact@v1
      with:
        name: CI_test_user_followers_3_${{ matrix.python-version }}

    # Run the new main files:
    - run: python CI_test_user_user_1_${{ matrix.python-version }}/user_film_compare_CI_user_user_1.py
    - run: python CI_test_user_user_2_${{ matrix.python-version }}/user_film_compare_CI_user_user_2.py
    - run: python CI_test_user_user_3_${{ matrix.python-version }}/user_film_compare_CI_user_user_3.py
    - run: python CI_test_user_following_1_${{ matrix.python-version }}/user_film_compare_CI_user_following_1.py
    - run: python CI_test_user_following_2_${{ matrix.python-version }}/user_film_compare_CI_user_following_2.py
    - run: python CI_test_user_following_3_${{ matrix.python-version }}/user_film_compare_CI_user_following_3.py
    - run: python CI_test_user_followers_1_${{ matrix.python-version }}/user_film_compare_CI_user_followers_1.py
    - run: python CI_test_user_followers_2_${{ matrix.python-version }}/user_film_compare_CI_user_followers_2.py
    - run: python CI_test_user_followers_3_${{ matrix.python-version }}/user_film_compare_CI_user_followers_3.py

    # Save the output files:
    - uses: actions/upload-artifact@v1
      with:
        name: CI_output_user_user_1_${{ matrix.python-version }}
        path: CI/user_film_compare_CI_user_user_1.txt
    - uses: actions/upload-artifact@v1
      with:
        name: CI_output_user_user_2_${{ matrix.python-version }}
        path: CI/user_film_compare_CI_user_user_2.txt
    - uses: actions/upload-artifact@v1
      with:
        name: CI_output_user_user_3_${{ matrix.python-version }}
        path: CI/user_film_compare_CI_user_user_3.txt
    - uses: actions/upload-artifact@v1
      with:
        name: CI_output_user_following_1_${{ matrix.python-version }}
        path: CI/user_film_compare_CI_user_following_1.csv
    - uses: actions/upload-artifact@v1
      with:
        name: CI_output_user_following_2_${{ matrix.python-version }}
        path: CI/user_film_compare_CI_user_following_2.csv
    - uses: actions/upload-artifact@v1
      with:
        name: CI_output_user_following_3_${{ matrix.python-version }}
        path: CI/user_film_compare_CI_user_following_3.csv
    - uses: actions/upload-artifact@v1
      with:
        name: CI_output_user_followers_1_${{ matrix.python-version }}
        path: CI/user_film_compare_CI_user_followers_1.csv
    - uses: actions/upload-artifact@v1
      with:
        name: CI_output_user_followers_2_${{ matrix.python-version }}
        path: CI/user_film_compare_CI_user_followers_2.csv
    - uses: actions/upload-artifact@v1
      with:
        name: CI_output_user_followers_3_${{ matrix.python-version }}
        path: CI/user_film_compare_CI_user_followers_3.csv

  # Another job called "CIcheck"
  CIcheck:

    # Needs output from earlier job:
    needs: CIrun
    runs-on: macos-latest

    # Loop through all python 3.x versions:
    strategy:
      matrix:
        python-version: [3.6,3.7,3.8]

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Checks-out the ability to run a python program here
    - uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Grab the needed outputs:
    - uses: actions/download-artifact@v1
      with:
        name: CI_output_user_user_1_${{ matrix.python-version }}
    - uses: actions/download-artifact@v1
      with:
        name: CI_output_user_user_2_${{ matrix.python-version }}
    - uses: actions/download-artifact@v1
      with:
        name: CI_output_user_user_3_${{ matrix.python-version }}
    - uses: actions/download-artifact@v1
      with:
        name: CI_output_user_following_1_${{ matrix.python-version }}
    - uses: actions/download-artifact@v1
      with:
        name: CI_output_user_following_2_${{ matrix.python-version }}
    - uses: actions/download-artifact@v1
      with:
        name: CI_output_user_following_3_${{ matrix.python-version }}
    - uses: actions/download-artifact@v1
      with:
        name: CI_output_user_followers_1_${{ matrix.python-version }}
    - uses: actions/download-artifact@v1
      with:
        name: CI_output_user_followers_2_${{ matrix.python-version }}
    - uses: actions/download-artifact@v1
      with:
        name: CI_output_user_followers_3_${{ matrix.python-version }}

    # Run the check program:
    - run: python CI/user_film_compare_results_check.py

    # Save the pass/fail output:
    # Save the output files:
    - uses: actions/upload-artifact@v1
      with:
        name: CI_results_${{ matrix.python-version }}
        path: CI/user_film_compare_results.txt

```
