### ISSUE TITLE
Automate Fork

### ISSUE THREAD

**Issue by Devils-Knight** [Devils-Knight/Automate-PR#3]
```yml
topic : 42Crunch
min_star : 0
total_pr : 1
```

**Comment by Devils-Knight** [comment]
Details of Secured workflow
```yml
    name: Yahua-elohim
    repo: POLICE-REMOTE-ADVANCED-TECHNOLOGY-SERVICES-PROTECTION-RESOURCES-REMOTE-DRONE-SURVEILLANCE
    path: .github/workflows/apd-workflow-2H72D2-analysis.yml
```

links:
repo: https://github.com/Yahua-elohim/POLICE-REMOTE-ADVANCED-TECHNOLOGY-SERVICES-PROTECTION-RESOURCES-REMOTE-DRONE-SURVEILLANCE
fork: https://github.com/Devils-Knight/POLICE-REMOTE-ADVANCED-TECHNOLOGY-SERVICES-PROTECTION-RESOURCES-REMOTE-DRONE-SURVEILLANCE

> Secured Workflow
```yml
# This workflow locates REST API file contracts
# (Swagger or OpenAPI format, v2 and v3, JSON and YAML)
# and runs 200+ security checks on them using 42Crunch Security Audit technology.
#
# Documentation is located here: https://docs.42crunch.com/latest/content/tasks/integrate_github_actions.htm
#
# To use this workflow, you will need to complete the following setup steps.
#
# 1. Create a free 42Crunch account at https://platform.42crunch.com/register
#
# 2. Follow steps at https://docs.42crunch.com/latest/content/tasks/integrate_github_actions.htm
#    to create an API Token on the 42Crunch platform
#
# 3. Add a secret in GitHub as explained in https://docs.42crunch.com/latest/content/tasks/integrate_github_actions.htm,
#    store the 42Crunch API Token in that secret, and supply the secret's name as api-token parameter in this workflow
#
# If you have any questions or need help contact https://support.42crunch.com

name: "42Crunch REST API Static Security Testing"

# follow standard Code Scanning triggers
on:
  push:
    branches: [ main ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ main ]
  schedule:
    - cron: '39 4 * * 0'

permissions:
  contents: read

jobs:
  rest-api-static-security-testing:
    permissions:
      contents: read  # for actions/checkout to fetch code
      security-events: write  # for 42Crunch/api-security-audit-action to upload results to Github Code Scanning
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: 42Crunch REST API Static Security Testing
        uses: 42Crunch/api-security-audit-action@v1
        with:
          # Please create free account at https://platform.42crunch.com/register
          # Follow these steps to configure API_TOKEN https://docs.42crunch.com/latest/content/tasks/integrate_github_actions.htm
          api-token: ${{ secrets.API_TOKEN }}
          # Fail if any OpenAPI file scores lower than 75
          min-score: 75
          # Upload results to Github code scanning
          upload-to-code-scanning: true
          # Github token for uploading the results
          github-token: ${{ github.token }}

```
