### ISSUE TITLE
Automate commit

### ISSUE THREAD

**Issue by Devils-Knight** [Devils-Knight/Automate-PR#4]
``` yml
topic : actions
min_star : 10
total_pr : 1
```

**Comment by Devils-Knight** [comment]
Details of Secured workflow
```yml
    name: Chuka-J-Uzo
    repo: Stock_Price_Collector_With_Emailing
    path: .github/workflows/apisec-scan-analysis.yml
```

links:
repo: https://github.com/Chuka-J-Uzo/Stock_Price_Collector_With_Emailing
fork: https://github.com/Devils-Knight/Stock_Price_Collector_With_Emailing

> Secured Workflow
```yml
# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# APIsec addresses the critical need to secure APIs before they reach production. 
# APIsec provides the industry’s only automated and continuous API testing platform that uncovers security vulnerabilities and logic flaws in APIs. 
# Clients rely on APIsec to evaluate every update and release, ensuring that no APIs go to production with vulnerabilities.

# How to Get Started with APIsec.ai
# 1. Schedule a demo at https://www.apisec.ai/request-a-demo .
#
# 2. Register your account at https://cloud.fxlabs.io/#/signup .
#
# 3. Register your API . See the video (https://www.youtube.com/watch?v=MK3Xo9Dbvac) to get up and running with APIsec quickly.
#
# 4. Get GitHub Actions scan attributes from APIsec Project -> Configurations -> Integrations -> CI-CD -> GitHub Actions
#
# apisec-run-scan
#
# This action triggers the on-demand scans for projects registered in APIsec.
# If your GitHub account allows code scanning alerts, you can then upload the sarif file generated by this action to show the scan findings.
# Else you can view the scan results from the project home page in APIsec Platform.
# The link to view the scan results is also displayed on the console on successful completion of action.

# This is a starter workflow to help you get started with APIsec-Scan Actions

name: APIsec

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  # Customize trigger events based on your DevSecOps processes.
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '15 3 * * 6'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


permissions:
  contents: read

jobs:
  Trigger APIsec scan:
    permissions:
      security-events: write  # for github/codeql-action/upload-sarif to upload SARIF results
    runs-on: ubuntu-latest

    steps:
       - name: APIsec scan
         uses: apisec-inc/apisec-run-scan@f62d0c6fae8a80f97b091a323befdb56e6ad9993
         with:
          # The APIsec username with which the scans will be executed
          apisec-username: ${{ secrets.apisec_username }}
          # The Password of the APIsec user with which the scans will be executed
          apisec-password: ${{ secrets.apisec_password}}
          # The name of the project for security scan
          apisec-project: "VAmPI"
          # The name of the sarif format result file The file is written only if this property is provided.
          sarif-result-file: "apisec-results.sarif"
       - name: Import results
         uses: github/codeql-action/upload-sarif@v1
         with:
          sarif_file: ./apisec-results.sarif

```

**Comment by Devils-Knight** [comment]
Details of Secured workflow
```yml
    name: joaolms
    repo: github-actions-continuous-delivery-azure
    path: .github/workflows/spinup-destroy.yml
```

links:
repo: https://github.com/joaolms/github-actions-continuous-delivery-azure
fork: https://github.com/Devils-Knight/github-actions-continuous-delivery-azure

> Secured Workflow
```yml
name: Configure Azure environment

on: 
  pull_request:
    types: [labeled]

env:
  PACKAGES_TOKEN: ${{secrets.PACKAGES_TOKEN}}
  AZURE_RESOURCE_GROUP: cd-with-actions
  AZURE_APP_PLAN: actions-ttt-deployment
  AZURE_LOCATION: '"Central US"'
  #################################################
  ### USER PROVIDED VALUES ARE REQUIRED BELOW   ###
  #################################################
  #################################################
  ### REPLACE USERNAME WITH GH USERNAME         ###
  AZURE_WEBAPP_NAME: joaolms-ttt-app
  #################################################

jobs:
  setup-up-azure-resources:
    runs-on: ubuntu-latest

    if: contains(github.event.pull_request.labels.*.name, 'spin up environment')

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Create Azure resource group
        if: success()
        run: |
          az group create --location ${{env.AZURE_LOCATION}} --name ${{env.AZURE_RESOURCE_GROUP}} --subscription ${{secrets.AZURE_SUBSCRIPTION_ID}}

      - name: Create Azure app service plan
        if: success()
        run: |
          az appservice plan create --resource-group ${{env.AZURE_RESOURCE_GROUP}} --name ${{env.AZURE_APP_PLAN}} --is-linux --sku F1 --subscription ${{secrets.AZURE_SUBSCRIPTION_ID}}

      - name: Create webapp resource
        if: success()
        run: |
          az webapp create --resource-group ${{ env.AZURE_RESOURCE_GROUP }} --plan ${{ env.AZURE_APP_PLAN }} --name ${{ env.AZURE_WEBAPP_NAME }}  --deployment-container-image-name nginx --subscription ${{secrets.AZURE_SUBSCRIPTION_ID}}

      - name: Configure webapp to use GitHub Packages
        if: success()
        run: |
          az webapp config container set --docker-custom-image-name nginx --docker-registry-server-password ${{secrets.GITHUB_TOKEN}} --docker-registry-server-url https://docker.pkg.github.com --docker-registry-server-user ${{github.actor}} --name ${{ env.AZURE_WEBAPP_NAME }} --resource-group ${{ env.AZURE_RESOURCE_GROUP }} --subscription ${{secrets.AZURE_SUBSCRIPTION_ID}}

  destroy-azure-resources:
    runs-on: ubuntu-latest

    if: contains(github.event.pull_request.labels.*.name, 'destroy environment')

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Destroy Azure environment
        if: success()
        run: |
          az group delete --name ${{env.AZURE_RESOURCE_GROUP}} --subscription ${{secrets.AZURE_SUBSCRIPTION_ID}} --yes

```

**Comment by Devils-Knight** [comment]
Details of Secured workflow
```yml
    name: W420-AB
    repo: dab1999
    path: .github/workflows/crunch42-analysis.yml
```

links:
repo: https://github.com/W420-AB/dab1999
fork: https://github.com/Devils-Knight/dab1999

> Secured Workflow
```yml
# This workflow locates REST API file contracts
# (Swagger or OpenAPI format, v2 and v3, JSON and YAML)
# and runs 200+ security checks on them using 42Crunch Security Audit technology.
#
# Documentation is located here: https://docs.42crunch.com/latest/content/tasks/integrate_github_actions.htm
#
# To use this workflow, you will need to complete the following setup steps.
#
# 1. Create a free 42Crunch account at https://platform.42crunch.com/register
#
# 2. Follow steps at https://docs.42crunch.com/latest/content/tasks/integrate_github_actions.htm
#    to create an API Token on the 42Crunch platform
#
# 3. Add a secret in GitHub as explained in https://docs.42crunch.com/latest/content/tasks/integrate_github_actions.htm,
#    store the 42Crunch API Token in that secret, and supply the secret's name as api-token parameter in this workflow
#
# If you have any questions or need help contact https://support.42crunch.com

name: "42Crunch REST API Static Security Testing"

# follow standard Code Scanning triggers
on:
  push:
    branches: [ main ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ main ]
  schedule:
    - cron: '21 8 * * 3'

permissions:
  contents: read

jobs:
  rest-api-static-security-testing:
    permissions:
      contents: read  # for actions/checkout to fetch code
      security-events: write  # for 42Crunch/api-security-audit-action to upload results to Github Code Scanning
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: 42Crunch REST API Static Security Testing
        uses: 42Crunch/api-security-audit-action@v1
        with:
          # Please create free account at https://platform.42crunch.com/register
          # Follow these steps to configure API_TOKEN https://docs.42crunch.com/latest/content/tasks/integrate_github_actions.htm
          api-token: ${{ secrets.API_TOKEN }}
          # Fail if any OpenAPI file scores lower than 75
          min-score: 75
          # Upload results to Github code scanning
          upload-to-code-scanning: true
          # Github token for uploading the results
          github-token: ${{ github.token }}

```

**Comment by Devils-Knight** [comment]
Details of Secured workflow
```yml
    name: briandfoy
    repo: mycpan-indexer
    path: .github/workflows/windows.yml
```

links:
repo: https://github.com/briandfoy/mycpan-indexer
fork: https://github.com/Devils-Knight/mycpan-indexer

> Secured Workflow
```yml
name: windows

on:
    push:
        branches:
            - '*'
        tags-ignore:
            - 'release-*'
        paths-ignore:
            - '.appveyor.yml'
            - '.github/**'
            - '.gitignore'
            - '.releaserc'
            - 'Changes'
            - 'LICENSE'
            - 'README.pod'
        pull_request:

permissions:
  contents: read

jobs:
    perl:
        runs-on: ${{ matrix.os }}
        strategy:
          matrix:
            os:
                - windows-2019
                - windows-2016

        steps:
            - uses: actions/checkout@v2
            - name: Set up Perl
              run: |
                choco install strawberryperl
                echo "C:\strawberry\c\bin"         >> $GITHUB_PATH
                echo "C:\strawberry\perl\site\bin" >> $GITHUB_PATH
                echo "C:\strawberry\perl\bin"      >> $GITHUB_PATH
            - name: Perl version
              run: perl -V
            - name: Install dependencies
              run: cpan -M https://www.cpan.org -T .
            - name: Run tests
              run: |
                perl Makefile.PL
                make test
            - name: Run parallel tests
              env:
                HARNESS_OPTIONS: 'j10'
              run: |
                perl Makefile.PL
                make test
            - name: Run dist tests
              run: |
                perl Makefile.PL
                make disttest

```
