### ISSUE TITLE
Add permissions for repo workflows

### ISSUE THREAD

**Issue by Devils-Knight** [Devils-Knight/Automate-PR#5]
```.yml
fix-repo
name : ampproject/amp-wp
```

**Comment by Devils-Knight** [comment]
Details of Secured workflow
```yml
    name: ampproject
    repo: amp-wp
    path: .github/workflows/codeql-analysis.yml
```

links:
repo: https://github.com/ampproject/amp-wp
fork: https://github.com/Devils-Knight/amp-wp

> Secured Workflow
```yml
name: CodeQL

# Cancel previous workflow run groups that have not completed.
concurrency:
  # Group workflow runs by workflow name, along with the head branch ref of the pull request
  # or otherwise the branch or tag ref.
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.head_ref || github.ref }}
  cancel-in-progress: true

on:
  push:
    # Only run if JS or Python files changed.
    paths:
      - '**.js'
      - '**.py'
    branches:
      - develop
      # Include all release branches.
      - '[0-9]+.[0-9]+'
  pull_request:
    # Only run if JS or Python files changed.
    paths:
      - '**.js'
      - '**.py'
    branches:
      - develop
      # Include all release branches.
      - '[0-9]+.[0-9]+'

permissions:
  contents: read

jobs:
  analyze:
    permissions:
      actions: read  # for github/codeql-action/init to get workflow details
      contents: read  # for actions/checkout to fetch code
      security-events: write  # for github/codeql-action/analyze to upload SARIF results
    name: Analyze
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v1
        with:
          languages: javascript, python

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v1

```
