### ISSUE TITLE
Add workflow permissions for ampproject/cdn-configuration

### ISSUE THREAD

**Issue by Devils-Knight** [Devils-Knight/Automate-PR#6]
```.yml
fix-repo
name : ampproject/cdn-configuration
```

**Comment by Devils-Knight** [comment]
Details of Secured workflow
```yml
    name: ampproject
    repo: cdn-configuration
    path: .github/workflows/ci.yml
```

links:
repo: https://github.com/ampproject/cdn-configuration
fork: https://github.com/Devils-Knight/cdn-configuration

> Secured Workflow
```yml
name: ci

on:
  pull_request:
    branches:
      - main

  push:
    branches:
      - main

  workflow_dispatch:

permissions:
  contents: read

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: lts/*

      - name: Install dependencies
        run: npm ci

      - name: Get diff
        id: get-diff
        run: |
          DIFF=$(git diff --name-only --diff-filter=ACMRT ${{ github.event.pull_request.base.sha }} ${{ github.sha }} | xargs)
          echo "::set-output name=diff::${DIFF}"

      - name: Run Prettier and ESLint
        run: |
          npm run prettier
          npm run lint

      - name: Run unit tests
        run: npx ts-mocha ./test/scripts/*.ts

      - name: Check configs
        run: npx ts-mocha ./test/check-json-schemas.ts

      - name: Check versions.json whitespace
        run: npx ts-mocha ./test/check-versions-whitespace.ts

      - name: Check file changes
        run: npx ts-mocha ./test/check-file-changes.ts --diff="${{ steps.get-diff.outputs.diff }}"

      - name: Check releases
        run: npx ts-mocha ./test/check-live-release.ts --diff="${{ steps.get-diff.outputs.diff }}"

```

**Comment by Devils-Knight** [comment]
Details of Secured workflow
```yml
    name: ampproject
    repo: cdn-configuration
    path: .github/workflows/ci.yml
```

links:
repo: https://github.com/ampproject/cdn-configuration
fork: https://github.com/Devils-Knight/cdn-configuration

> Secured Workflow
```yml
name: ci

on:
  pull_request:
    branches:
      - main

  push:
    branches:
      - main

  workflow_dispatch:

permissions:
  contents: read

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: lts/*

      - name: Install dependencies
        run: npm ci

      - name: Get diff
        id: get-diff
        run: |
          DIFF=$(git diff --name-only --diff-filter=ACMRT ${{ github.event.pull_request.base.sha }} ${{ github.sha }} | xargs)
          echo "::set-output name=diff::${DIFF}"

      - name: Run Prettier and ESLint
        run: |
          npm run prettier
          npm run lint

      - name: Run unit tests
        run: npx ts-mocha ./test/scripts/*.ts

      - name: Check configs
        run: npx ts-mocha ./test/check-json-schemas.ts

      - name: Check versions.json whitespace
        run: npx ts-mocha ./test/check-versions-whitespace.ts

      - name: Check file changes
        run: npx ts-mocha ./test/check-file-changes.ts --diff="${{ steps.get-diff.outputs.diff }}"

      - name: Check releases
        run: npx ts-mocha ./test/check-live-release.ts --diff="${{ steps.get-diff.outputs.diff }}"

```

**Comment by Devils-Knight** [comment]
Details of Secured workflow
```yml
    name: ampproject
    repo: cdn-configuration
    path: .github/workflows/promote-beta-experimental-traffic.yml
```

links:
repo: https://github.com/ampproject/cdn-configuration
fork: https://github.com/Devils-Knight/cdn-configuration

> Secured Workflow
```yml
# Promotes the current Beta/Experimental opt-in channels to traffic channels on a schedule.

name: Promote Beta/Experimental traffic Channels

on:
  schedule:
    # 1:30 a.m. PST / 12:30 a.m. PDT, Wednesdays.
    - cron: '30 1 * * 3'

  workflow_dispatch:
    inputs:
      amp-version:
        description: 'AMP version number (13 digits)'
        required: false
        default: ''
        type: string
      auto-merge:
        description: 'Enable PR auto-merge'
        required: false
        type: boolean

permissions:
  contents: read

jobs:
  promote-beta-experimental-traffic:
    permissions:
      contents: none
    uses: ampproject/cdn-configuration/.github/workflows/promote-reusable-workflow.yml@main
    with:
      channel-name: 'Beta/Experimental traffic'
      ts-file: 'promote-beta-experimental-traffic.ts'
      amp-version: ${{ github.event.inputs.amp-version }}
      auto-merge: ${{ github.event.inputs.auto-merge }}
    secrets:
      access-token: ${{ secrets.ACCESS_TOKEN }}

```

**Comment by Devils-Knight** [comment]
Details of Secured workflow
```yml
    name: ampproject
    repo: cdn-configuration
    path: .github/workflows/promote-cherry-picks.yml
```

links:
repo: https://github.com/ampproject/cdn-configuration
fork: https://github.com/Devils-Knight/cdn-configuration

> Secured Workflow
```yml
# Promotes the cherry-picked release into all related channels
# Triggered by circleci job on amphtml

name: Promote Cherry-Picks

on:
  workflow_dispatch:
    inputs:
      amp-version:
        description: 'AMP version number (13 digits)'
        required: true
        type: string
      auto-merge:
        description: 'Enable PR auto-merge'
        required: true
        default: true
        type: boolean

permissions:
  contents: read

jobs:
  promote-cherry-picks:
    permissions:
      contents: none
    uses: ampproject/cdn-configuration/.github/workflows/promote-reusable-workflow.yml@main
    with:
      channel-name: 'Cherry-pick'
      ts-file: 'promote-cherry-picks.ts'
      amp-version: ${{ github.event.inputs.amp-version }}
      auto-merge: ${{ github.event.inputs.auto-merge }}
    secrets:
      access-token: ${{ secrets.ACCESS_TOKEN }}

```

**Comment by Devils-Knight** [comment]
Details of Secured workflow
```yml
    name: ampproject
    repo: cdn-configuration
    path: .github/workflows/promote-lts.yml
```

links:
repo: https://github.com/ampproject/cdn-configuration
fork: https://github.com/Devils-Knight/cdn-configuration

> Secured Workflow
```yml
# Promotes the current Stable channel to LTS on a schedule.
name: Promote LTS Channel

on:
  schedule:
    # 1:30 a.m. PST / 12:30 a.m. PDT, Mondays.
    # Note that the job itself ensures it is running on the 2nd Monday of the
    # month, since crontab does not support this condition.
    - cron: '30 1 * * 1'

  workflow_dispatch:
    inputs:
      amp-version:
        description: 'AMP version number (13 digits)'
        required: false
        default: ''
        type: string
      auto-merge:
        description: 'Enable PR auto-merge'
        required: false
        type: boolean

permissions:
  contents: read

jobs:
  get-day:
    permissions:
      contents: none
    runs-on: ubuntu-latest
    outputs:
      day: ${{ steps.day.outputs.day }}
    steps:
      - name: Get day of the month
        id: day
        run: echo "::set-output name=day::$(date +%d)"

  promote-lts:
    permissions:
      contents: none
    needs: get-day
    # The 2nd Monday always falls between the 8th to the 14th of the month (inclusive).
    if: github.event.inputs.amp-version || (8 <= needs.get-day.outputs.day && needs.get-day.outputs.day <= 14)
    uses: ampproject/cdn-configuration/.github/workflows/promote-reusable-workflow.yml@main
    with:
      channel-name: 'LTS'
      ts-file: 'promote-lts.ts'
      amp-version: ${{ github.event.inputs.amp-version }}
      auto-merge: ${{ github.event.inputs.auto-merge }}
    secrets:
      access-token: ${{ secrets.ACCESS_TOKEN }}

```

**Comment by Devils-Knight** [comment]
Details of Secured workflow
```yml
    name: ampproject
    repo: cdn-configuration
    path: .github/workflows/qa-label.yml
```

links:
repo: https://github.com/ampproject/cdn-configuration
fork: https://github.com/Devils-Knight/cdn-configuration

> Secured Workflow
```yml
name: QA Label

on:
  pull_request:
    paths:
      - 'configs/versions.json'

permissions:
  contents: read

jobs:
  qa-label:
    permissions:
      contents: none
    if: startsWith(github.head_ref, 'promote-job-stable') || startsWith(github.head_ref, 'promote-job-beta-experimental-traffic')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v4
        with:
          repo-token: ${{ secrets.ACCESS_TOKEN }}

```
