### ISSUE TITLE
Add workflow permissions for ant-design/ant-design

### ISSUE THREAD

**Issue by Devils-Knight** [Devils-Knight/Automate-PR#9]
```yml
fix-repo
name : ant-design/ant-design
```

**Comment by Devils-Knight** [comment]
Details of Secured workflow
```yml
    name: ant-design
    repo: ant-design
    path: .github/workflows/compressed-size.yml
```

links:
repo: https://github.com/ant-design/ant-design
fork: https://github.com/Devils-Knight/ant-design

> Secured Workflow
```yml
name: 📦 Compressed Size

on:
  pull_request:
    types: [opened, synchronize]

permissions:
  contents: read

jobs:
  compressed-size:
    permissions:
      checks: write  # for preactjs/compressed-size-action to create and update the checks
      contents: read  # for actions/checkout to fetch code
      issues: write  # for preactjs/compressed-size-action to create comments
      pull-requests: write  # for preactjs/compressed-size-action to write a PR review
    runs-on: ubuntu-latest
    env:
      CI_JOB_NUMBER: 1

    steps:
    - uses: actions/checkout@v3
    - uses: preactjs/compressed-size-action@v2
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        pattern: "./dist/**/*.min.{js,css}"
        build-script: "dist:esbuild-no-dup-check"
        clean-script: "clean-lockfiles"

```

**Comment by Devils-Knight** [comment]
Details of Secured workflow
```yml
    name: ant-design
    repo: ant-design
    path: .github/workflows/preview-build.yml
```

links:
repo: https://github.com/ant-design/ant-design
fork: https://github.com/Devils-Knight/ant-design

> Secured Workflow
```yml
# Each PR will build preview site that help to check code is work as expect.

name: Preview Build

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read

jobs:
  # Prepare node modules. Reuse cache if available
  setup:
    name: prepare preview
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: cache package-lock.json
        uses: actions/cache@v3
        with:
          path: package-temp-dir
          key: lock-${{ github.sha }}

      - name: create package-lock.json
        run: npm i --package-lock-only --ignore-scripts

      - name: hack for single file
        run: |
          if [ ! -d "package-temp-dir" ]; then
            mkdir package-temp-dir
          fi
          cp package-lock.json package-temp-dir
      - name: cache node_modules
        id: node_modules_cache_id
        uses: actions/cache@v3
        with:
          path: node_modules
          key: node_modules-${{ hashFiles('**/package-temp-dir/package-lock.json') }}

      - name: install
        if: steps.node_modules_cache_id.outputs.cache-hit != 'true'
        run: npm ci

  build-site:
    name: build preview
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: restore cache from package-lock.json
        uses: actions/cache@v3
        with:
          path: package-temp-dir
          key: lock-${{ github.sha }}

      - name: restore cache from node_modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: node_modules-${{ hashFiles('**/package-temp-dir/package-lock.json') }}

      - name: npm run site
        id: site
        run: npm run site
        env:
          SITE_ENV: development

      - name: upload site artifact
        uses: actions/upload-artifact@v3
        with:
          name: site
          path: _site/
          retention-days: 5

      # Upload PR id for next workflow use
      - name: Save PR number
        if: ${{ always() }}
        run: echo ${{ github.event.number }} > ./pr-id.txt

      - name: Upload PR number
        if: ${{ always() }}
        uses: actions/upload-artifact@v3
        with:
          name: pr
          path: ./pr-id.txt

```

**Comment by Devils-Knight** [comment]
Details of Secured workflow
```yml
    name: ant-design
    repo: ant-design
    path: .github/workflows/rebase.yml
```

links:
repo: https://github.com/ant-design/ant-design
fork: https://github.com/Devils-Knight/ant-design

> Secured Workflow
```yml
name: Automatic Rebase

on:
  issue_comment:
    types: [created]

permissions:
  contents: read

jobs:
  rebase:
    permissions:
      contents: write  # for cirrus-actions/rebase to push code to rebase
      pull-requests: read  # for cirrus-actions/rebase to get info about PR
    name: Rebase
    if: github.event.issue.pull_request != '' && (contains(github.event.comment.body, '/rebase') || contains(github.event.comment.body, '\rebase'))
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Automatic Rebase
      uses: cirrus-actions/rebase@1.5
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

```

**Comment by Devils-Knight** [comment]
Details of Secured workflow
```yml
    name: ant-design
    repo: ant-design
    path: .github/workflows/test.yml
```

links:
repo: https://github.com/ant-design/ant-design
fork: https://github.com/Devils-Knight/ant-design

> Secured Workflow
```yml
# Origin Source
# https://github.com/ant-design/ant-design/blob/79f566b7f8abb1012ef55b0d2793bfdf5595b85d/.github/workflows/test.yml
name: ✅ test

on: [push, pull_request]

permissions:
  contents: read

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: cache package-lock.json
        uses: actions/cache@v3
        with:
          path: package-temp-dir
          key: lock-${{ github.sha }}

      - name: create package-lock.json
        run: npm i --package-lock-only --ignore-scripts

      - name: hack for single file
        run: |
          if [ ! -d "package-temp-dir" ]; then
            mkdir package-temp-dir
          fi
          cp package-lock.json package-temp-dir
      - name: cache node_modules
        id: node_modules_cache_id
        uses: actions/cache@v3
        with:
          path: node_modules
          key: node_modules-${{ hashFiles('**/package-temp-dir/package-lock.json') }}

      - name: install
        if: steps.node_modules_cache_id.outputs.cache-hit != 'true'
        run: npm ci

  compile:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: restore cache from package-lock.json
        uses: actions/cache@v3
        with:
          path: package-temp-dir
          key: lock-${{ github.sha }}

      - name: restore cache from node_modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: node_modules-${{ hashFiles('**/package-temp-dir/package-lock.json') }}

      - name: cache lib
        uses: actions/cache@v3
        with:
          path: lib
          key: lib-${{ github.sha }}

      - name: cache es
        uses: actions/cache@v3
        with:
          path: es
          key: es-${{ github.sha }}

      - name: compile
        run: npm run compile

      - name: check
        run: node ./tests/dekko/lib.test.js
    needs: setup

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: restore cache from package-lock.json
        uses: actions/cache@v3
        with:
          path: package-temp-dir
          key: lock-${{ github.sha }}

      - name: restore cache from node_modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: node_modules-${{ hashFiles('**/package-temp-dir/package-lock.json') }}

      - name: lint
        run: npm run lint
    needs: setup

  tsx-demo:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: restore cache from package-lock.json
        uses: actions/cache@v3
        with:
          path: package-temp-dir
          key: lock-${{ github.sha }}

      - name: restore cache from node_modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: node_modules-${{ hashFiles('**/package-temp-dir/package-lock.json') }}

      - name: tsx-demo
        run: npm run check-ts-demo
    needs: setup

  check_metadata:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: restore cache from package-lock.json
        uses: actions/cache@v3
        with:
          path: package-temp-dir
          key: lock-${{ github.sha }}

      - name: restore cache from node_modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: node_modules-${{ hashFiles('**/package-temp-dir/package-lock.json') }}

      - name: check demo
        run: node ./scripts/check-demo.js
    needs: setup

  react-17-dom:
    name: react@17.x / dom
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: restore cache from package-lock.json
        uses: actions/cache@v3
        with:
          path: package-temp-dir
          key: lock-${{ github.sha }}

      - name: restore cache from node_modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: node_modules-${{ hashFiles('**/package-temp-dir/package-lock.json') }}

      - name: test
        run: npm test -- -w 1 --coverage

      - name: coverage
        run: bash <(curl -s https://codecov.io/bash)
    needs: setup

  react-17-node:
    name: react@17.x / node
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: restore cache from package-lock.json
        uses: actions/cache@v3
        with:
          path: package-temp-dir
          key: lock-${{ github.sha }}

      - name: restore cache from node_modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: node_modules-${{ hashFiles('**/package-temp-dir/package-lock.json') }}

      - name: test
        run: npm run test-node
    needs: setup

  react-17-lib:
    name: react@17.x / lib
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: restore cache from package-lock.json
        uses: actions/cache@v3
        with:
          path: package-temp-dir
          key: lock-${{ github.sha }}

      - name: restore cache from node_modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: node_modules-${{ hashFiles('**/package-temp-dir/package-lock.json') }}

      - name: restore cache from lib
        uses: actions/cache@v3
        with:
          path: lib
          key: lib-${{ github.sha }}

      - name: test
        run: npm test
        env:
          LIB_DIR: lib
    needs: compile

  react-17-es:
    name: react@17.x / es
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: restore cache from package-lock.json
        uses: actions/cache@v3
        with:
          path: package-temp-dir
          key: lock-${{ github.sha }}

      - name: restore cache from node_modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: node_modules-${{ hashFiles('**/package-temp-dir/package-lock.json') }}

      - name: restore cache from es
        uses: actions/cache@v3
        with:
          path: es
          key: es-${{ github.sha }}

      - name: test
        run: npm test
        env:
          LIB_DIR: es
    needs: compile

  react-17-dist:
    name: react@17.x / dist
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: restore cache from package-lock.json
        uses: actions/cache@v3
        with:
          path: package-temp-dir
          key: lock-${{ github.sha }}

      - name: restore cache from node_modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: node_modules-${{ hashFiles('**/package-temp-dir/package-lock.json') }}

      - name: dist
        run: npm run dist
        env:
          NODE_OPTIONS: --max_old_space_size=4096

      - name: check
        run: node ./tests/dekko/dist.test.js

      - name: bundlesize
        run: npm run bundlesize
        env:
          BUNDLESIZE_GITHUB_TOKEN: ${{ secrets.BUNDLESIZE_GITHUB_TOKEN }}

      - name: test
        run: npm test
        env:
          LIB_DIR: dist
    needs: setup

  react-16-dom:
    name: react@16.x / dom
    runs-on: ubuntu-latest
    env:
      REACT: 16
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: restore cache from package-lock.json
        uses: actions/cache@v3
        with:
          path: package-temp-dir
          key: lock-${{ github.sha }}

      - name: restore cache from node_modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: node_modules-${{ hashFiles('**/package-temp-dir/package-lock.json') }}

      - name: install react 16
        run: npm run install-react-16

      - name: test
        run: npm test -- -w 1 --coverage
    needs: setup

  react-16-node:
    name: react@16.x / node
    runs-on: ubuntu-latest
    env:
      REACT: 16
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: restore cache from package-lock.json
        uses: actions/cache@v3
        with:
          path: package-temp-dir
          key: lock-${{ github.sha }}

      - name: restore cache from node_modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: node_modules-${{ hashFiles('**/package-temp-dir/package-lock.json') }}

      - name: install react 16
        run: npm run install-react-16

      - name: test
        run: npm run test-node
    needs: setup

  react-16-lib:
    name: react@16.x / lib
    runs-on: ubuntu-latest
    env:
      REACT: 16
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: restore cache from package-lock.json
        uses: actions/cache@v3
        with:
          path: package-temp-dir
          key: lock-${{ github.sha }}

      - name: restore cache from node_modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: node_modules-${{ hashFiles('**/package-temp-dir/package-lock.json') }}

      - name: restore cache from lib
        uses: actions/cache@v3
        with:
          path: lib
          key: lib-${{ github.sha }}

      - name: install react 16
        run: npm run install-react-16

      - name: test
        run: npm test
        env:
          LIB_DIR: lib
    needs: compile

  react-16-es:
    name: react@16.x / es
    runs-on: ubuntu-latest
    env:
      REACT: 16
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: restore cache from package-lock.json
        uses: actions/cache@v3
        with:
          path: package-temp-dir
          key: lock-${{ github.sha }}

      - name: restore cache from node_modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: node_modules-${{ hashFiles('**/package-temp-dir/package-lock.json') }}

      - name: restore cache from es
        uses: actions/cache@v3
        with:
          path: es
          key: es-${{ github.sha }}

      - name: install react 16
        run: npm run install-react-16

      - name: test
        run: npm test
        env:
          LIB_DIR: es
    needs: compile

  react-16-dist:
    name: react@16.x / dist
    runs-on: ubuntu-latest
    env:
      REACT: 16
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: restore cache from package-lock.json
        uses: actions/cache@v3
        with:
          path: package-temp-dir
          key: lock-${{ github.sha }}

      - name: restore cache from node_modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: node_modules-${{ hashFiles('**/package-temp-dir/package-lock.json') }}

      - name: install react 16
        run: npm run install-react-16

      - name: dist
        run: npm run dist
        env:
          NODE_OPTIONS: --max_old_space_size=4096

      - name: check
        run: node ./tests/dekko/dist.test.js

      - name: test
        run: npm test
        env:
          LIB_DIR: dist
    needs: setup

  style:
    name: style compile
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: restore cache from package-lock.json
        uses: actions/cache@v3
        with:
          path: package-temp-dir
          key: lock-${{ github.sha }}

      - name: restore cache from node_modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: node_modules-${{ hashFiles('**/package-temp-dir/package-lock.json') }}

      - name: compile
        run: npm run compile

      - name: dist
        run: npm run dist
        env:
          NODE_OPTIONS: --max_old_space_size=4096

      - name: lessc default
        run: npx lessc --js ./dist/antd.less

      - name: lessc dark
        run: npx lessc --js ./dist/antd.dark.less

      - name: lessc variable
        run: npx lessc --js ./dist/antd.variable.less

      - name: lessc component
        run: npx lessc --js ./es/button/style/index.less

      - name: lessc mixins
        run: npx lessc --js ./es/style/mixins/index.less
    needs: setup

```

**Comment by Devils-Knight** [comment]
Details of Secured workflow
```yml
    name: ant-design
    repo: ant-design
    path: .github/workflows/ui-upload.yml
```

links:
repo: https://github.com/ant-design/ant-design
fork: https://github.com/Devils-Knight/ant-design

> Secured Workflow
```yml
# Upload 📷 UI snapshots to argos server, help visual regression testing.

name: UI Upload

on:
  workflow_run:
    workflows: ["📷 UI"]
    types:
      - completed

permissions:
  contents: read

jobs:
  upload-ui:
    permissions:
      actions: read  # for dawidd6/action-download-artifact to query and download artifacts
      pull-requests: read  # for dawidd6/action-download-artifact to query commit hash
    name: deploy preview
    runs-on: ubuntu-latest
    if: >
      github.event.workflow_run.conclusion == 'success'
    steps:
      - name: Download commit artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: ${{ github.event.workflow_run.workflow_id }}
          name: commit

      - name: Save commit id
        id: commit
        run: echo "::set-output name=id::$(<commit.txt)"

      - name: Download branch artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: ${{ github.event.workflow_run.workflow_id }}
          name: branch

      - name: Save branch id
        id: branch
        run: echo "::set-output name=id::$(<branch.txt)"

      - name: Download snapshots artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: ${{ github.event.workflow_run.workflow_id }}
          workflow_conclusion: success
          name: snapshots

      - name: Upload argos-ci
        id: deploy
        run: |
          npx argos-cli upload ./ --token ${{ secrets.ARGOS_TOKEN }} --branch ${{ steps.branch.outputs.id }} --commit ${{ steps.commit.outputs.id }}

```

**Comment by Devils-Knight** [comment]
Details of Secured workflow
```yml
    name: ant-design
    repo: ant-design
    path: .github/workflows/ui.yml
```

links:
repo: https://github.com/ant-design/ant-design
fork: https://github.com/Devils-Knight/ant-design

> Secured Workflow
```yml
name: 📷 UI

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - master

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: cache package-lock.json
        uses: actions/cache@v3
        with:
          path: package-temp-dir
          key: lock-${{ github.sha }}

      - name: create package-lock.json
        run: npm i --package-lock-only --ignore-scripts

      - name: hack for single file
        run: |
          if [ ! -d "package-temp-dir" ]; then
            mkdir package-temp-dir
          fi
          cp package-lock.json package-temp-dir
      - name: cache node_modules
        id: node_modules_cache_id
        uses: actions/cache@v3
        with:
          path: node_modules
          key: node_modules-${{ hashFiles('**/package-temp-dir/package-lock.json') }}

      - name: install
        if: steps.node_modules_cache_id.outputs.cache-hit != 'true'
        run: npm ci

      - name: test
        run: npm run test-image

      - name: upload snapshots artifact
        uses: actions/upload-artifact@v3
        with:
          name: snapshots
          path: imageSnapshots/
          retention-days: 3

      - name: Save commit
        if: github.event_name == 'pull_request' && github.base_ref == 'master'
        run: echo ${{ github.event.pull_request.head.sha }} > ./commit.txt

      - name: Save commit
        if: github.event_name == 'push'
        run: echo ${{ github.sha }} > ./commit.txt

      - name: Upload commit
        if: ${{ always() }}
        uses: actions/upload-artifact@v3
        with:
          name: commit
          path: ./commit.txt

      - name: Save branch
        if: github.event_name == 'pull_request' && github.base_ref == 'master'
        run: echo pull/${{ github.event.pull_request.number }}/merge > ./branch.txt

      - name: Save branch
        if: github.event_name == 'push'
        run: echo ${GITHUB_REF##*/} > ./branch.txt

      - name: Upload branch
        if: ${{ always() }}
        uses: actions/upload-artifact@v3
        with:
          name: branch
          path: ./branch.txt

```
